export default function PrivacyPage() {
  return (
    <div style={{ background:'#020817', minHeight:'100vh', color:'#e2e8f0', fontFamily:'system-ui,sans-serif' }}>
      <div style={{ maxWidth:780, margin:'0 auto', padding:'80px 24px' }}>
        <div style={{ marginBottom:48 }}>
          <p style={{ fontSize:12, color:'#6366F1', fontWeight:600, textTransform:'uppercase', letterSpacing:'0.1em', marginBottom:12 }}>Legal</p>
          <h1 style={{ fontSize:40, fontWeight:800, color:'white', marginBottom:8 }}>Privacy Policy</h1>
          <p style={{ color:'#64748B', fontSize:14 }}>Last updated: May 2026</p>
        </div>

        {[
          { title:'1. Who we are', body:'Sho8lana ("we", "our", "us") is an Egypt-based HR technology platform connecting students and employers through simulation-based hiring. Our platform is accessible at sho8lana.vercel.app.' },
          { title:'2. Information we collect', body:'We collect information you provide directly (name, email, university, CV documents), information generated by your use of the platform (simulation results, KPI scores, XP, application history), and technical information (IP address, browser type, device identifiers) for security and analytics purposes. We also receive basic profile data (name, email, avatar) when you sign in via Google or GitHub OAuth.' },
          { title:'3. How we use your information', body:'We use your data to provide and improve our services, display your KPI profile to verified employers, send transactional emails (application confirmations, interview invites), process payments through Stripe, and comply with legal obligations. We do not sell your personal data to third parties.' },
          { title:'4. Data sharing', body:'We share data with: (a) employers who access our talent marketplace — they see your anonymized KPI score until you apply or they unlock your full profile; (b) Stripe for payment processing; (c) Supabase for secure data storage; (d) Resend for email delivery. All third parties are bound by appropriate data protection agreements.' },
          { title:'5. Data retention', body:'We retain your account data for as long as your account is active. You may request deletion of your account and associated data at any time by contacting privacy@sho8lana.com. Aggregated, anonymized analytics data may be retained indefinitely.' },
          { title:'6. Security', body:'We use industry-standard security measures including TLS encryption in transit, Supabase Row Level Security for data isolation, bcrypt password hashing, and optional TOTP multi-factor authentication. However, no system is perfectly secure and we cannot guarantee absolute security.' },
          { title:'7. Your rights', body:'You have the right to access, correct, or delete your personal data. You may update your profile information at any time from the Profile screen. To request full data export or deletion, contact privacy@sho8lana.com. If you are in the EU/EEA, you have additional rights under GDPR.' },
          { title:'8. Cookies', body:'We use essential cookies for session management and authentication. We do not use advertising or tracking cookies. You can disable cookies in your browser settings, but this may affect platform functionality.' },
          { title:'9. Children', body:'Our platform is intended for university students aged 18 and older. We do not knowingly collect data from anyone under 18. If you believe a minor has registered, contact us immediately.' },
          { title:'10. Changes', body:'We may update this policy periodically. We will notify registered users of material changes via email. Continued use of the platform after changes constitutes acceptance of the updated policy.' },
          { title:'11. Contact', body:'For privacy-related questions or requests: privacy@sho8lana.com' },
        ].map(s => (
          <div key={s.title} style={{ marginBottom:36, paddingBottom:36, borderBottom:'1px solid rgba(255,255,255,0.06)' }}>
            <h2 style={{ fontSize:18, fontWeight:700, color:'white', marginBottom:10 }}>{s.title}</h2>
            <p style={{ fontSize:14, color:'#94A3B8', lineHeight:1.8 }}>{s.body}</p>
          </div>
        ))}

        <div style={{ marginTop:48, paddingTop:24, borderTop:'1px solid rgba(255,255,255,0.06)' }}>
          <a href="/" style={{ color:'#6366F1', textDecoration:'none', fontSize:14, fontWeight:600 }}>← Back to Sho8lana</a>
        </div>
      </div>
    </div>
  )
}
