// ── The Forage: curated simulation program catalog ─────────────────────────────
// Real programs sourced from theforage.com — used as the primary dataset in the
// /api/forage route, with live-fetch attempted first on every request.

export type ForageCategory =
  | 'Finance'
  | 'Technology'
  | 'Consulting'
  | 'Data'
  | 'Engineering'
  | 'Marketing'

export type ForageLevel = 'Beginner' | 'Intermediate'

export interface ForageProgram {
  id: string
  company: string
  initials: string
  color: string
  category: ForageCategory
  title: string
  duration: string
  tasks: number
  skills: string[]
  level: ForageLevel
  description: string
  url: string
  enrolled: string
  rating: number
  hot?: boolean
}

export const FORAGE_CATEGORIES: ForageCategory[] = [
  'Finance', 'Technology', 'Consulting', 'Data', 'Engineering', 'Marketing',
]

export const FORAGE_PROGRAMS: ForageProgram[] = [

  // ── Finance ──────────────────────────────────────────────────────────────────
  {
    id: 'gs-excel',
    company: 'Goldman Sachs',
    initials: 'GS',
    color: '#2C3E7B',
    category: 'Finance',
    title: 'Excel Skills for Business',
    duration: '5–6 hrs',
    tasks: 6,
    skills: ['Excel', 'Financial Modeling', 'Pivot Tables', 'Data Analysis'],
    level: 'Beginner',
    description: 'Master the Excel skills Goldman Sachs analysts use daily — from data cleaning to financial models.',
    url: 'https://www.theforage.com/simulations?q=goldman+sachs',
    enrolled: '150k+',
    rating: 4.8,
    hot: true,
  },
  {
    id: 'jpmc-ib',
    company: 'JPMorgan Chase',
    initials: 'JP',
    color: '#A01E26',
    category: 'Finance',
    title: 'Investment Banking Virtual Experience',
    duration: '4–5 hrs',
    tasks: 4,
    skills: ['Valuation', 'DCF', 'Pitchbooks', 'Financial Modeling'],
    level: 'Beginner',
    description: 'Work through real IB deal workflows — comparable analysis, pitch decks, and valuation models.',
    url: 'https://www.theforage.com/simulations?q=jpmorgan+investment+banking',
    enrolled: '90k+',
    rating: 4.7,
  },
  {
    id: 'deloitte-audit',
    company: 'Deloitte',
    initials: 'DL',
    color: '#86BC25',
    category: 'Finance',
    title: 'Audit Virtual Experience',
    duration: '3–4 hrs',
    tasks: 3,
    skills: ['Auditing', 'Risk Assessment', 'IFRS', 'Internal Controls'],
    level: 'Beginner',
    description: 'Audit a real client engagement. Learn risk identification, testing, and documentation.',
    url: 'https://www.theforage.com/simulations?q=deloitte+audit',
    enrolled: '65k+',
    rating: 4.6,
  },
  {
    id: 'anz-banking',
    company: 'ANZ Bank',
    initials: 'AN',
    color: '#007DBA',
    category: 'Finance',
    title: 'Commercial Banking Virtual Internship',
    duration: '4–5 hrs',
    tasks: 5,
    skills: ['Commercial Banking', 'Credit Analysis', 'Customer Relations', 'Finance'],
    level: 'Beginner',
    description: 'Experience banking operations, credit assessment, and relationship management at ANZ.',
    url: 'https://www.theforage.com/simulations?q=anz+banking',
    enrolled: '55k+',
    rating: 4.5,
  },
  {
    id: 'pwc-digital',
    company: 'PwC',
    initials: 'PW',
    color: '#E0301E',
    category: 'Finance',
    title: 'Digital Intelligence Program',
    duration: '4–5 hrs',
    tasks: 4,
    skills: ['Digital Transformation', 'Analytics', 'Technology Strategy', 'Finance'],
    level: 'Beginner',
    description: "Experience how PwC combines technology and finance to deliver digital transformation.",
    url: 'https://www.theforage.com/simulations?q=pwc+digital',
    enrolled: '80k+',
    rating: 4.6,
  },
  {
    id: 'redbull-finance',
    company: 'Red Bull',
    initials: 'RB',
    color: '#CC1E1E',
    category: 'Finance',
    title: 'Corporate Finance & Commercial Experience',
    duration: '3–4 hrs',
    tasks: 3,
    skills: ['Financial Analysis', 'Brand Management', 'Commercial Strategy', 'Pricing'],
    level: 'Beginner',
    description: 'Work in the commercial team at Red Bull. Pricing, portfolio analysis, and brand strategy.',
    url: 'https://www.theforage.com/simulations?q=red+bull',
    enrolled: '45k+',
    rating: 4.7,
  },

  // ── Technology ────────────────────────────────────────────────────────────────
  {
    id: 'jpmc-se',
    company: 'JPMorgan Chase',
    initials: 'JP',
    color: '#A01E26',
    category: 'Technology',
    title: 'Software Engineering Experience',
    duration: '5–6 hrs',
    tasks: 5,
    skills: ['Python', 'React', 'TypeScript', 'Financial APIs'],
    level: 'Intermediate',
    description: 'Fix bugs, implement features, and visualize stock data — just like a JPMorgan engineer.',
    url: 'https://www.theforage.com/simulations?q=jpmorgan+software+engineering',
    enrolled: '120k+',
    rating: 4.8,
    hot: true,
  },
  {
    id: 'deloitte-tech',
    company: 'Deloitte',
    initials: 'DL',
    color: '#86BC25',
    category: 'Technology',
    title: 'Technology Virtual Experience',
    duration: '5–6 hrs',
    tasks: 5,
    skills: ['Cloud Computing', 'Cybersecurity', 'AI', 'Digital Strategy'],
    level: 'Beginner',
    description: 'Experience Deloitte technology consulting — cloud strategy, security, and innovation.',
    url: 'https://www.theforage.com/simulations?q=deloitte+technology',
    enrolled: '85k+',
    rating: 4.7,
  },
  {
    id: 'ea-se',
    company: 'Electronic Arts',
    initials: 'EA',
    color: '#FF4747',
    category: 'Technology',
    title: 'Software Engineering Virtual Experience',
    duration: '5–6 hrs',
    tasks: 5,
    skills: ['C++', 'Object-Oriented Design', 'Game Development', 'Code Review'],
    level: 'Intermediate',
    description: 'Build features for real EA games. Write production-quality code in a game studio.',
    url: 'https://www.theforage.com/simulations?q=electronic+arts+software',
    enrolled: '70k+',
    rating: 4.7,
  },
  {
    id: 'skyscanner-fe',
    company: 'Skyscanner',
    initials: 'SC',
    color: '#0770CF',
    category: 'Technology',
    title: 'Frontend Engineering Experience',
    duration: '5–6 hrs',
    tasks: 5,
    skills: ['React', 'JavaScript', 'CSS', 'A/B Testing', 'UI/UX'],
    level: 'Intermediate',
    description: 'Build and ship frontend features on the Skyscanner travel platform — real codebase, real review.',
    url: 'https://www.theforage.com/simulations?q=skyscanner+frontend',
    enrolled: '60k+',
    rating: 4.8,
  },
  {
    id: 'cognizant-ai',
    company: 'Cognizant',
    initials: 'CG',
    color: '#0033A0',
    category: 'Technology',
    title: 'Artificial Intelligence Experience',
    duration: '5–6 hrs',
    tasks: 5,
    skills: ['Machine Learning', 'Python', 'Pandas', 'Model Evaluation'],
    level: 'Intermediate',
    description: 'Build ML models for real client scenarios. Data prep, training, and model evaluation.',
    url: 'https://www.theforage.com/simulations?q=cognizant+artificial+intelligence',
    enrolled: '95k+',
    rating: 4.6,
  },
  {
    id: 'aws-architect',
    company: 'AWS',
    initials: 'AW',
    color: '#FF9900',
    category: 'Technology',
    title: 'Solutions Architecture Experience',
    duration: '5–6 hrs',
    tasks: 5,
    skills: ['AWS', 'Cloud Architecture', 'S3', 'Lambda', 'System Design'],
    level: 'Beginner',
    description: 'Design AWS cloud solutions for real business scenarios. No prior cloud experience required.',
    url: 'https://www.theforage.com/simulations?q=aws+solutions+architecture',
    enrolled: '100k+',
    rating: 4.7,
    hot: true,
  },
  {
    id: 'mastercard-cyber',
    company: 'Mastercard',
    initials: 'MC',
    color: '#EB001B',
    category: 'Technology',
    title: 'Cybersecurity Virtual Experience',
    duration: '5–6 hrs',
    tasks: 5,
    skills: ['Cybersecurity', 'Phishing Detection', 'Risk Analysis', 'Security Awareness'],
    level: 'Beginner',
    description: 'Defend Mastercard from phishing attacks — real threat analysis and security strategy.',
    url: 'https://www.theforage.com/simulations?q=mastercard+cybersecurity',
    enrolled: '110k+',
    rating: 4.7,
  },
  {
    id: 'walmart-se',
    company: 'Walmart',
    initials: 'WM',
    color: '#0071DC',
    category: 'Technology',
    title: 'Advanced Software Engineering',
    duration: '5–6 hrs',
    tasks: 6,
    skills: ['Java', 'Python', 'Data Structures', 'System Architecture', 'Database Design'],
    level: 'Intermediate',
    description: 'Solve engineering challenges at one of the world\'s largest tech companies.',
    url: 'https://www.theforage.com/simulations?q=walmart+software+engineering',
    enrolled: '85k+',
    rating: 4.8,
  },
  {
    id: 'lyft-backend',
    company: 'Lyft',
    initials: 'LF',
    color: '#FF00BF',
    category: 'Technology',
    title: 'Back-End Engineering Experience',
    duration: '5–6 hrs',
    tasks: 5,
    skills: ['Python', 'OOP', 'SOLID Principles', 'Unit Testing', 'Refactoring'],
    level: 'Intermediate',
    description: 'Refactor a Lyft fleet system. Apply SOLID principles to real production code.',
    url: 'https://www.theforage.com/simulations?q=lyft+back-end+engineering',
    enrolled: '75k+',
    rating: 4.7,
  },
  {
    id: 'tata-cyber',
    company: 'Tata Group',
    initials: 'TA',
    color: '#0057A8',
    category: 'Technology',
    title: 'Cybersecurity Analyst Experience',
    duration: '5–6 hrs',
    tasks: 5,
    skills: ['Cybersecurity', 'Network Security', 'Threat Detection', 'Risk Management'],
    level: 'Beginner',
    description: 'Protect Tata digital infrastructure — threat analysis, incident response, and strategy.',
    url: 'https://www.theforage.com/simulations?q=tata+cybersecurity',
    enrolled: '90k+',
    rating: 4.6,
  },
  {
    id: 'commonwealth-se',
    company: 'Commonwealth Bank',
    initials: 'CB',
    color: '#F5A800',
    category: 'Technology',
    title: 'Software Engineering Experience',
    duration: '5–6 hrs',
    tasks: 5,
    skills: ['Java', 'REST APIs', 'Security', 'Agile', 'Software Testing'],
    level: 'Intermediate',
    description: 'Build and test banking software at Commonwealth Bank. Real agile workflow.',
    url: 'https://www.theforage.com/simulations?q=commonwealth+bank+software',
    enrolled: '65k+',
    rating: 4.6,
  },

  // ── Consulting ────────────────────────────────────────────────────────────────
  {
    id: 'bcg-strategy',
    company: 'BCG',
    initials: 'BC',
    color: '#00A651',
    category: 'Consulting',
    title: 'Strategy Consulting Experience',
    duration: '5–6 hrs',
    tasks: 5,
    skills: ['Business Strategy', 'Market Analysis', 'Financial Modeling', 'Presentations'],
    level: 'Beginner',
    description: 'Solve a real strategy problem with BCG — data analysis, client comms, and recommendations.',
    url: 'https://www.theforage.com/simulations?q=bcg+strategy+consulting',
    enrolled: '130k+',
    rating: 4.8,
    hot: true,
  },
  {
    id: 'accenture-strategy',
    company: 'Accenture',
    initials: 'AC',
    color: '#A100FF',
    category: 'Consulting',
    title: 'Strategy Consulting Program',
    duration: '5–6 hrs',
    tasks: 5,
    skills: ['Strategy', 'Business Analysis', 'Change Management', 'Innovation'],
    level: 'Beginner',
    description: 'Work on an Accenture engagement. Analyze markets, build strategy, present to clients.',
    url: 'https://www.theforage.com/simulations?q=accenture+strategy+consulting',
    enrolled: '125k+',
    rating: 4.7,
  },
  {
    id: 'kpmg-consulting',
    company: 'KPMG',
    initials: 'KP',
    color: '#00338D',
    category: 'Consulting',
    title: 'Data Analytics Consulting',
    duration: '5–6 hrs',
    tasks: 5,
    skills: ['Power BI', 'Business Intelligence', 'Data Quality', 'Analytics'],
    level: 'Beginner',
    description: 'Analyze client data and deliver insights for a real KPMG consulting engagement.',
    url: 'https://www.theforage.com/simulations?q=kpmg+data+analytics',
    enrolled: '115k+',
    rating: 4.7,
  },

  // ── Data ──────────────────────────────────────────────────────────────────────
  {
    id: 'accenture-data',
    company: 'Accenture',
    initials: 'AC',
    color: '#A100FF',
    category: 'Data',
    title: 'Data Analytics & Visualization',
    duration: '5–6 hrs',
    tasks: 6,
    skills: ['Tableau', 'Excel', 'Data Visualization', 'Statistical Analysis', 'Storytelling'],
    level: 'Beginner',
    description: 'Analyze datasets and build dashboards for an Accenture client. Storytelling with data.',
    url: 'https://www.theforage.com/simulations?q=accenture+data+analytics',
    enrolled: '145k+',
    rating: 4.9,
    hot: true,
  },
  {
    id: 'hsbc-data',
    company: 'HSBC',
    initials: 'HS',
    color: '#DB0011',
    category: 'Data',
    title: 'Data Science Experience',
    duration: '5–6 hrs',
    tasks: 5,
    skills: ['Python', 'Machine Learning', 'Banking Data', 'Data Analysis'],
    level: 'Intermediate',
    description: 'Apply data science to real HSBC banking scenarios — raw data to actionable insights.',
    url: 'https://www.theforage.com/simulations?q=hsbc+data+science',
    enrolled: '70k+',
    rating: 4.6,
  },
  {
    id: 'commonwealth-data',
    company: 'Commonwealth Bank',
    initials: 'CB',
    color: '#F5A800',
    category: 'Data',
    title: 'Data Science Experience',
    duration: '5–6 hrs',
    tasks: 5,
    skills: ['Python', 'SQL', 'Data Analysis', 'Machine Learning', 'Visualization'],
    level: 'Intermediate',
    description: "Solve Commonwealth Bank's data challenges with real financial datasets and ML.",
    url: 'https://www.theforage.com/simulations?q=commonwealth+bank+data',
    enrolled: '60k+',
    rating: 4.6,
  },

  // ── Engineering ───────────────────────────────────────────────────────────────
  {
    id: 'ge-engineering',
    company: 'GE Aerospace',
    initials: 'GE',
    color: '#0F4ED7',
    category: 'Engineering',
    title: 'Engineering Virtual Experience',
    duration: '5–6 hrs',
    tasks: 5,
    skills: ['Mechanical Engineering', 'Systems Design', 'Problem Solving', 'CAD'],
    level: 'Beginner',
    description: 'Work on GE Aerospace engineering challenges — design, optimization, and innovation.',
    url: 'https://www.theforage.com/simulations?q=ge+engineering',
    enrolled: '40k+',
    rating: 4.5,
  },
  {
    id: 'siemens-engineering',
    company: 'Siemens',
    initials: 'SI',
    color: '#009999',
    category: 'Engineering',
    title: 'Electrical Engineering Experience',
    duration: '5–6 hrs',
    tasks: 4,
    skills: ['Electrical Engineering', 'Power Systems', 'PLC', 'Circuit Design'],
    level: 'Intermediate',
    description: 'Experience Siemens engineering — circuit analysis, industrial automation, and power systems.',
    url: 'https://www.theforage.com/simulations?q=siemens+engineering',
    enrolled: '35k+',
    rating: 4.5,
  },

  // ── Marketing ─────────────────────────────────────────────────────────────────
  {
    id: 'accenture-marketing',
    company: 'Accenture Song',
    initials: 'AS',
    color: '#A100FF',
    category: 'Marketing',
    title: 'Digital Marketing Experience',
    duration: '4–5 hrs',
    tasks: 4,
    skills: ['Digital Marketing', 'SEO', 'Content Strategy', 'Social Media', 'Analytics'],
    level: 'Beginner',
    description: 'Run a full digital marketing campaign for an Accenture client — strategy to execution.',
    url: 'https://www.theforage.com/simulations?q=accenture+marketing',
    enrolled: '55k+',
    rating: 4.6,
  },
]
